name: kliniku
description: "kliniku - Aplikasi Manajemen Klinik"

publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  # ğŸŒ Localization (WAJIB)
  flutter_localizations:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  intl: ^0.20.2

  # ğŸ”¥ Firebase
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1

  # PDF
  pdf: ^3.11.0
  printing: ^5.13.1
  rename: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo_klinikiku.png

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/static/Roboto-Regular.ttf
        - asset: assets/fonts/static/Roboto-Bold.ttf
          weight: 700
